### ISSUE TITLE
Issue & pull_request_templates

### ISSUE THREAD

**Issue by ritiksoni00** [anushbhatia/Social-Scheduler#10]
can I add those File To project so that Everyone has clarity for making an issue or PR ??

**Comment by Jyotika999** [comment]
Can I work on this issue?

**Comment by ritiksoni00** [comment]
currently, I'm working and I'm not the assigned but if you want, you can make Issue_template File. EASYY

**Comment by anushbhatia** [comment]
We are looking PRs related to the code.

**Comment by ritiksoni00** [comment]
> We are looking PRs related to the code.
is this not Require ??
