### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by anushbhatia** [anushbhatia/Social-Scheduler#12]
Any Relevant Actions To Be Used can be mentioned here

**Comment by rohitgeddam** [comment]
please add lint test

**Comment by sayashchaudhary** [comment]
can I set-up eslint for this project ?

**Comment by AltCtrlDel1999** [comment]
@ashishnagpal2498 I would like to work on this issue

**Comment by ashishnagpal2498** [comment]
still working on the issue @AltCtrlDel1999 ?

**Comment by AltCtrlDel1999** [comment]
Can you suggest any link to know about github Actions 
I tried one but getting Error

**Comment by AltCtrlDel1999** [comment]
I will complete it by tomorrow

**Comment by rajatgoel47** [comment]
can I work on this issue?

**Comment by ashishnagpal2498** [comment]
Sure @rajatgoel47 . Assigning it to you.
