### ISSUE TITLE
Add details to setup the application on the local environment

### ISSUE THREAD

**Issue by abhu-A-J** [anushbhatia/Social-Scheduler#18]
**README.md Update**

Add detailed information about how to set up the application on your local machine for future participants to use it as a resource.

You must include detailed steps which should cover:
1. Installing dependencies 
2. Serving the application
3. Remove the section for available scripts.

Mention Node.js as a requirement for the link and maybe a few resources to help install in different OS.
Also, make a link to contributing guidelines (which already exists) from the Readme.md to avoid any confusion.

**Open to anyone**

**Comment by ritiksoni00** [comment]
can i start??

**Comment by ritiksoni00** [comment]
This type of work na??

**Comment by ritiksoni00** [comment]
> Mention Node.js as a requirement for the link and maybe a few resources to help install in different OS.

Didnt get this !

**Comment by abhu-A-J** [comment]
> This type of work na??
> ![Annotation 2020-08-16 234948](https://user-images.githubusercontent.com/47344024/90341204-34a21e00-e01b-11ea-8d9e-c3c846313672.png)

Yup thats' correct! Mention Node.js as the requirement to setup the project and maybe add a few resources that show how to install node.js in out Operating System (MAC,Windows,Linux)

**Comment by abhu-A-J** [comment]
@ritiksoni00 Are you still interested? I'll assign this ti someone else if you don't complete it by tonight!

**Comment by ritiksoni00** [comment]
sorry for delay!

**Comment by ritiksoni00** [comment]
clear this whole part! little bit confused so just asking ![image](https://user-images.githubusercontent.com/47344024/90761061-73c4bd80-e300-11ea-8b30-839ef7a24c14.png)

**Comment by ritiksoni00** [comment]
@abhu-A-J  it should be closed now??
