### ISSUE TITLE
Update the dependecies to the latest version 

### ISSUE THREAD

**Issue by abhu-A-J** [anushbhatia/Social-Scheduler#20]
Update all the dependencies for the project to the latest version and make sure to correct any breaking changes whatsoever.
Also audit fix any vulnerabilities found while doing so.

**Comment by Souvikns** [comment]
For this, I think we could add [dependabot ](https://dependabot.com/) to maintain our dependencies

**Comment by abhu-A-J** [comment]
> For this, I think we could add [dependabot ](https://dependabot.com/) to maintain our dependencies

That's a great idea! But the reason I created this was for absolute beginners to make their first PR.

**Comment by sayashchaudhary** [comment]
Can i update the dependencies in this project
