### ISSUE TITLE
Design a new logo for the application

### ISSUE THREAD

**Issue by abhu-A-J** [anushbhatia/Social-Scheduler#21]
Create a custom logo for the application. You can use services from Adobe or any other service which will help you deliver the best logo.

The logo must be available in `.PNG` and `SVG` format and must be within 200*200 px at max.

The issue is open for all,so anyone can contribute to it.
 Raise your PR to branch `logo_samples`.

**Open for Everyone!! (10 people maximum)**.

Comment down if you're willing to work on the issue!

**Comment by ritiksoni00** [comment]
ill work on that

**Comment by abhu-A-J** [comment]
> ill work on that, but need some info what type and looks are we preferring

You can reach out to admin for some inspiration or idea! He can guide you for UI/UX related issues! But anything which can either explain the app or similar will be accepted!

**Comment by anushbhatia** [comment]
Any Help you can feel free to contact me

**Comment by ritiksoni00** [comment]
is it hard or medium?? @abhu-A-J

**Comment by abhu-A-J** [comment]
> is it hard or medium?? @abhu-A-J

We'll give points based on the design of the logo!

**Comment by abhu-A-J** [comment]
@ritiksoni00 Progress on this?

**Comment by utchak160** [comment]
Assign this task to me.

**Comment by abhu-A-J** [comment]
> Assign this task to me.

Go for it! Make sure to make a PR on appropriate branch!

**Comment by ritiksoni00** [comment]
> @ritiksoni00 Progress on this?

sorry for the delay, I was on my rest days! start working from today

**Comment by chetnaSharma24** [comment]
hello @abhu-A-J  could you please assign this to me

**Comment by trybick** [comment]
@abhu-A-J Are you still accepting new logo ideas? (for hacktoberfest)

**Comment by smaranjitghose** [comment]
No.

But if you want to contribute some custom logos, feel free to give a PR to:
- [Doc2Pen](https://github.com/smaranjitghose/doc2pen)
- [Awesome Portfolio Websites](https://github.com/smaranjitghose/awesome-portfolio-websites)
