### ISSUE TITLE
Dynamic content for contributers

### ISSUE THREAD

**Issue by Souvikns** [anushbhatia/Social-Scheduler#25]
As in #7 the details of the contributors, I would like to use Github API to fetch dynamic data and update the component. This away we don't have to update the webpage every time a new contributor arrives. We already have a pr #19, I will use this view, but the data will be fetched through Github API. 

Check [this](https://developer.github.com/v3/repos/statistics/) for API

**Comment by Souvikns** [comment]
@abhu-A-J will you assign this to me

**Comment by abhu-A-J** [comment]
Go for it! Make use of hooks and functional components instead of class-based components
