### ISSUE TITLE
Add the corrections/suggestions given by linters

### ISSUE THREAD

**Issue by abhu-A-J** [anushbhatia/Social-Scheduler#31]
Clear all console logs warning related to linting and errors for cross dependencies for JQuery for the project.

**Comment by Electron-2002** [comment]
@abhu-A-J Can you assign this to me?

**Comment by abhu-A-J** [comment]
> @abhu-A-J Can you assign this to me?

Go for it! Since it's very basic I'm giving you 12 hrs ! After that the issue will be re assigned!

**Comment by Electron-2002** [comment]
@abhu-A-J  I sent a PR. I was unable to link it to this issue. 
Kindly check the PR. 

Sorry for any inconvenience caused from my side. 😅
