### ISSUE TITLE
Adding a custom 404 component for Default Page

### ISSUE THREAD

**Issue by abhu-A-J** [anushbhatia/Social-Scheduler#32]
Currenly the details page displays a basic `Page Not Found Message`.

The PR should improve this by showing a custom 404 component (with some animations ) and `Page Not Found Text` 
and a button to go back to home page on click.

The 404 components must be made separately.
Place the 404 along with it styles in the following folder/path:

1. Create a folder called 404-page inside components folder.
2. The 404-page must have a .jsx file and it associated styles.
3. Import this component and put it in Default Page

**Comment by kashika3101** [comment]
Please assign it to me.
I would like to work on this issue

**Comment by avinashkranjan** [comment]
I'll take this issue..Assign Ms

**Comment by abhu-A-J** [comment]
@kashika3101  I'm assigning this to you since you commented first!
@avinashkranjan watch out for other issue, I will be creating some more!

**Comment by abhu-A-J** [comment]
@kashika3101 What's the update here?

**Comment by rohan2734** [comment]
@abhu-A-J  can u assign me the task of "whatsapp message with sekenium" in Form Page. I commented there first , but no one is caring about that.Please look after that

**Comment by kashika3101** [comment]
@abhu-A-J I'm about to make a PR

**Comment by abhu-A-J** [comment]
> @abhu-A-J I'm about to make a PR

Update?? I will assign it to someone else if you don't submit it by today!

**Comment by shankhanil007** [comment]
I would like to work on this issue.
