### ISSUE TITLE
Improve the fetchUsers hook!

### ISSUE THREAD

**Issue by abhu-A-J** [anushbhatia/Social-Scheduler#33]
The fetch Users hook present inside the `/lib` folder needs a small update.

The purpose of the hook is to fetch the list of all the contributors for the project! 
We need to filter out the accounts for our admins `anushbhatia` and `smaranjitghose` and possible mentors including me `abhu-A-J`.

You need to improve the map mehod where we return out all contributors except these 3.

In addition that that crate two new files on the folder `data` from where we can an array of objects describing admin and mentor details (same format which we get from GITHUB API).

**Comment by Souvikns** [comment]
@abhu-A-J I would like to do this.

**Comment by abhu-A-J** [comment]
> @abhu-A-J I would like to do this.

Go ahead !
