### ISSUE TITLE
Create _redirect file for netlify

### ISSUE THREAD

**Issue by Souvikns** [anushbhatia/Social-Scheduler#38]
Currently prs are struggling because netlify's redirect rules. I would like to add the redirect file for netlify

**Comment by smaranjitghose** [comment]
Can you please elaborate more and explain with an example

**Comment by Souvikns** [comment]
Currently, the hosted website in [netlify](https://social-scheduler.netlify.app/) has an issue. 
suppose you go to contact page which is on `https://social-scheduler.netlify.app/contact` it will work just fine but if you refresh the page it will `page not found` error from netlify. Also when you try to go to any route manually by typing the link in the browser search you will get this same error.

![image](https://user-images.githubusercontent.com/41781438/90410480-06c6e300-e0c8-11ea-99e9-e33007f4bb3b.png)

**Comment by Souvikns** [comment]
@smaranjitghose will you please assign me this issue.

**Comment by Souvikns** [comment]
my previous pr was approved but not merged yet, so when I pushed the code for this issue it went there. #35

**Comment by Souvikns** [comment]
@smaranjitghose this error issue is fixed, when you merged the #35

**Comment by abhu-A-J** [comment]
@Souvikns I think this issue is solved?? I'm closing it. If some work is still left let me know, I'll re open it!
