### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by anushbhatia** [anushbhatia/Social-Scheduler#4]
Description of various events being displayed and a basic description of the project
[Events Page](https://www.townscript.com/in/vadodara)

- [ ] Have a basic Home Page listing Descriptions
- [ ] Video Playing in intro with optimization
- [ ]  Cards
- [ ] Footer
- [ ] Navbar

For events use upcoming open source events

**Comment by Shruti3004** [comment]
@anushbhatia I wanted to know are you having any mockup for home page

**Comment by anushbhatia** [comment]
Sure go on

**Comment by rohan2734** [comment]
hello , I would like to work on video playing in intro with optimization. can you explain me , what are the things required for this?

**Comment by anushbhatia** [comment]
do u know how to make videos

**Comment by chetnaSharma24** [comment]
hii,
I would like to work upon this issue , 
I will  add the footer section in it.
😊
@anushbhatia

**Comment by shawavisek35** [comment]
I would to like to work upon the navbar section.

**Comment by Nazeeh2000** [comment]
I would like to work upon the Description listing.

**Comment by Nazeeh2000** [comment]
For now, I will add some Lorem Ipsum in description

**Comment by rohan2734** [comment]
@anushbhatia i will learn and do , I will do it in a very short time. Please tell me what are things to know.

**Comment by Nazeeh2000** [comment]
Ohk if you want to work on that then u can continue

**Comment by srishtij2000** [comment]
I would like to work on cards section

**Comment by rohan2734** [comment]
@anushbhatia   could you please asign me the task of  video playing in intro, i learned it now and i know how to do that.

**Comment by utchak160** [comment]
Can I work on a basic Home Page listing Descriptions?

**Comment by Shruti3004** [comment]
@anushbhatia we can modify the navigation icon

**Comment by srishtij2000** [comment]
Can I work on cards section?
