### ISSUE TITLE
Mentors and admins cards

### ISSUE THREAD

**Issue by abhu-A-J** [anushbhatia/Social-Scheduler#47]
Only work after #46 is resolved.

Use the card component created in #46 and pass it with appropriate props to produce the admin and mentors card.
The details of mentors and admin will be static and should be present in the folder `data/adminList.js` and `data/mentorList.js`.
The details should be present as array of objects (object describing the details of the person -i mage, name and tagline . You can fetch the data from the GitHub API and the store it as a static list or write down the details yourself.

**Comment by Souvikns** [comment]
as `data/admin.js` and `data/mentorList.js` is arrays, Should I make some changes so that `contributors.js` returns three objects, for admin, mentor and contributors each.

**Comment by utchak160** [comment]
Please assign this task to me.

**Comment by abhu-A-J** [comment]
@Souvikns @utchak160  You can make a named export from both file with an array of objects for admins and mentors. 
There' no need to changed contributors.js since admin and mentor list is very small and we can easily write the list ourselves .
in future if the list expands we'll update our scripts.

@utchak160 I'm assigning you this one since @Souvikns had worked on this part already!.

**Comment by Souvikns** [comment]
@abhu-A-J I think as we are getting all the data from the API so we do have all the data during sorting out, we should change the `contributors.js` file. Suppose in future anyone changes their profile data in github it will be reflected in the data automatically.

**Comment by abhu-A-J** [comment]
> @abhu-A-J I think as we are getting all the data from the API so we do have all the data during sorting out, we should change the `contributors.js` file. Suppose in future anyone changes their profile data in github it will be reflected in the data automatically.

@Souvikns That's the way to do it! :+1: The reason I wanted a static list was if the API call fails I want just this static list of mentors and admins to render out. However, there are many ways to doing this so I am opening this up for further discussion and tagging another mentor for his insight on this (@ashishnagpal2498  thoughts??) :smile:

**Comment by Souvikns** [comment]
I would have really like to do this, but since you have assigned someone is there any other work, that I can do.

**Comment by abhu-A-J** [comment]
> I would have really like to do this, but since you have assigned someone is there any other work, that I can do.

We'll come up with plenty more issues soon! Since a lot of PR are under review it os blocking further steps for the application. Once they get merged , there will be more things to work on!

**Comment by utchak160** [comment]
This issue can be closed.
