### ISSUE TITLE
Form Page

### ISSUE THREAD

**Issue by anushbhatia** [anushbhatia/Social-Scheduler#5]
This page will have a form which when filled will sent them message of the deadlines and important events 

- [ ] Basic Form Structure : assigned to @rohan2734 
- [x] Basic Email Message: addition of send Email function as a util : assigned to @Souvikns (done)
- [ ] LinkedIn Message Using Visor API: assigned to @rohan2734 (In- progress)
- [x] Whatsapp Message using selenium : assigned to @rohan2734 (done)

**Comment by chetnaSharma24** [comment]
I would like to work upon the **Basic form structure**

**Comment by Souvikns** [comment]
I would like to work on **Basic Email Message**.

**Comment by anushbhatia** [comment]
@chetnaSharma24 First finish your previous task then i will assign you this @Souvikns will have this issue for 5 days

**Comment by Souvikns** [comment]
are there any specific third party email api that I should be using

**Comment by Souvikns** [comment]
Also for the form design I had made a view like typeform. Tell me If I should make something similar. [here](https://mcu-web.onrender.com/coreform)

**Comment by Souvikns** [comment]
@anushbhatia please will you clear my doubts

**Comment by anushbhatia** [comment]
Formspree can br used but we can different forms of Event forms. So we can add them

**Comment by Souvikns** [comment]
Also what inputs should I be talking from the forms

**Comment by srishtij2000** [comment]
I would like to work on basic form structure

**Comment by rohan2734** [comment]
@anushbhatia  I would like to work on whatsapp mesage using selenium. could you please assign that task to me.

**Comment by anushbhatia** [comment]
basic details name,phone number,email,their social media handles

**Comment by kartikeya-123** [comment]
I would like to work on the basic form structure

**Comment by rohan2734** [comment]
@anushbhatia  i would like to work on whatsapp message using selenium. Could you please assign me this task.

**Comment by utchak160** [comment]
Can I work on LinkedIn Message task?

**Comment by rohan2734** [comment]
is there any mentor here who could assign me the task of sending "whatsapp message using selenium" ??. please assign me this task.

**Comment by rohan2734** [comment]
I am posting this twice. because there is no reply for this comment. Please assign me this task mentors of  "whatsapp message using selenium" ??

**Comment by abhu-A-J** [comment]
> I am posting this twice. because there is no reply for this comment. Please assign me this task mentors of "whatsapp message using selenium" ??

Go for it! Also mentors will reply so not to worry about it in the future!

**Comment by rohan2734** [comment]
Thanks for assigning me, i will start working on it.

**Comment by utchak160** [comment]
Please assign me the Basic Form Structure task

**Comment by AltCtrlDel1999** [comment]
Hey @abhu-A-J @anushbhatia I would like to work on basic form structure and LinkedIn visitor API

**Comment by rohan2734** [comment]
Basic Form Page for signin Page is done , now as @ashishnagpal2498  has promised me to give the signin page aslo. I request @ashishnagpal2498  to assign me that task also.

**Comment by rohan2734** [comment]
@anushbhatia  @ashishnagpal2498  @abhu-A-J  as the task : ``` LinkedIn Message Using Visor AP``` is assigned to @AltCtrlDel1999  but he has not done it , i would like to work on it.

**Comment by ashishnagpal2498** [comment]
Okay @rohan2734 , you can start working on LinkedIn Message API.
