### ISSUE TITLE
Design for HomePage

### ISSUE THREAD

**Issue by abhu-A-J** [anushbhatia/Social-Scheduler#54]
This is strictly a design issue and involves no coding experience.
You have to come up with a design for the HomePage for the application to the best of your abilities.

For every design  you make, make sure to share a link from where we can export resources to build the design for the application.
Using Figma as the design tool would be great but you can do with whatever tool you're comfortable with.

Share your screenshot below for the design, so we can pick the best one. All PR's for designs will be merged if they meet the requirement and steps to raise PR will be given with time when we get more designs.

This is Open for all and anyone can contribute to it.

**Comment by utchak160** [comment]
Okay

**Comment by utchak160** [comment]
> > https://www.figma.com/file/PpJW9qriwtS4RgIUSwDdpI/Untitled?node-id=0%3A1
> 
> Good Work @utchak160 . Let me know when it is verified by @anushbhatia and I'll tell you the further steps for PR and merging this!

The design is complete.

**Comment by ashishnagpal2498** [comment]
add a json file - features.json Add design as key and figma link as value. Create a pull request and you'll get points for this issue :)

**Comment by utchak160** [comment]
Ok, I'll do it.
