### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by sayashchaudhary** [anushbhatia/Social-Scheduler#57]
For eg - assets folder should be outside the components folder and shared components should be inside shared folders

**Comment by sayashchaudhary** [comment]
Can i start working on it

**Comment by abhu-A-J** [comment]
> Can i start working on it

It seems there are still some issues pending ! You need to wait till PR's get merged. I'll tag you in here when you can do it. Till then you can take any other issue to work on.
