### ISSUE TITLE
Register form component for user defined in footer part 

### ISSUE THREAD

**Issue by AltCtrlDel1999** [anushbhatia/Social-Scheduler#59]
Register button present in footer does nothing 

- [x] Add a Register form which can take user data

- [x] Modification in footer : Add a link to fork the repository of the social scheduler

**Comment by AltCtrlDel1999** [comment]
@abhu-A-J @anushbhatia I would like to work on this issue

**Comment by shankhanil007** [comment]
Can I work on this issue?
