### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by anushbhatia** [anushbhatia/Social-Scheduler#6]
For content add a Lorem Ipsum as of now further content will be shared

- [x] Graphics form [undraw.co](undraw.co)
- [x] Add logos of various Social Media: Instagram, Facebook, Whatsapp, Linkedin 
- [ ] Features Section
- [ ] Try not using cards in this instead of having something more of simple.

**Comment by rohitgeddam** [comment]
I want to do this

**Comment by aayushi2883** [comment]
I would like to work upon it

**Comment by anushbhatia** [comment]
@rohitgeddam Complete these tasks 
Graphics form undraw.co
Add logos of various Social Media: Instagram, Facebook, Whatsapp, Linkedin

@aayushi2883 You can create features like [this](https://themeisle.com/demo/?theme=Hestia)

**Comment by rohitgeddam** [comment]
i already made a PR

**Comment by Nazeeh2000** [comment]
I would like to work upon this issue

**Comment by Nazeeh2000** [comment]
I would like to work on this issue

**Comment by anushbhatia** [comment]
- [ ] Features Section
- [ ] Try not using cards in this instead having something more of simple.

**Comment by srishtij2000** [comment]
I would like to work on this issue

**Comment by AshutoshDash1999** [comment]
@anushbhatia can i work on features section?

**Comment by sayashchaudhary** [comment]
Can i implement the About Us page with better UI and better usage of the social icons

**Comment by kartikeya-123** [comment]
I would like to work on features section. Can I know what features are to be added .

**Comment by anushbhatia** [comment]
@aayushi2883 has 1 day left then you can continue @kartikeya-123

**Comment by kartikeya-123** [comment]
@anushbhatia  please assign me the features section issue. I would like to work on it. Can you brief me about what exactly the features should be like.

**Comment by kartikeya-123** [comment]
> @aayushi2883 has 1 day left then you can continue @kartikeya-123

Can I start with the features section.

**Comment by kartikeya-123** [comment]
@anushbhatia  can you please brief me about the features that to be added and I want to know whether I can use react-bootstrap .

**Comment by anushbhatia** [comment]
yes, you can use react-bootstrap.
- Regular Updates
- Fast
- Reliable
- Prior Information to Deadline

**Comment by sayashchaudhary** [comment]
Can you tell more about the features section

**Comment by anushbhatia** [comment]
https://demos.creative-tim.com/material-kit-pro/sections.html#features
