### ISSUE TITLE
create a issue and pull request template

### ISSUE THREAD

**Issue by AltCtrlDel1999** [anushbhatia/Social-Scheduler#64]

**Comment by AltCtrlDel1999** [comment]
I would like to work on it

**Comment by AltCtrlDel1999** [comment]
Currently, people are making issues and PR's without a proper format and description
So we can make templates so that they can fill info according to that templates
check this out: [](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

**Comment by AltCtrlDel1999** [comment]
[https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository](url)

**Comment by sayashchaudhary** [comment]
link is not opening

**Comment by anushbhatia** [comment]
add a proper URL

**Comment by AltCtrlDel1999** [comment]
[](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

**Comment by AltCtrlDel1999** [comment]
[https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository](url)

**Comment by AltCtrlDel1999** [comment]
[Check this out](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

**Comment by anushbhatia** [comment]
you can do this

**Comment by tusharnankani** [comment]
Can I work on the templates?
