### ISSUE TITLE
Create header

### ISSUE THREAD

**Issue by ashishnagpal2498** [anushbhatia/Social-Scheduler#66]
You need to create a header component for the project.
1) It should have logo and existing options ->  Logo, Home , about, Contributors Contact and SignIn option.
2) For logo place a dummy image and display text beside it.
3) On hover text should be underlined. (Use color code from the image.)
4) SignIn option should have a user icon, onclick a dropdown menu.
5) Mobile view of the header should look same as current view.
*Prefer using flex-box*
![header](https://user-images.githubusercontent.com/36301481/92249859-53902380-eee8-11ea-88c9-6ff3dc955407.png)

Everything should be properly aligned and responsive. Use styled components and bootstrap.

**Comment by rutujadhanawade** [comment]
I would like to work on this

**Comment by ashishnagpal2498** [comment]
Okay @rutujadhanawade . Assigning it to you. You got 5 days to complete it. Kindly fulfill all the requirements mentioned above in your PR.

**Comment by ashishnagpal2498** [comment]
Keep in mind, your first PR is not supposed to be the best but a starting point for meeting the requirements, so do not wait until 5 days to show your work. Keep pushing your commits and getting feedback.

**Comment by ashishnagpal2498** [comment]
What's the status of PR?

**Comment by rutujadhanawade** [comment]
Yes I am doing it.  I will make PR soon.

**Comment by rutujadhanawade** [comment]
Actually I am unable to complete it due to some issues. I am unassigning myself.

**Comment by nikita-1801** [comment]
I'd like to work on this.

**Comment by ashishnagpal2498** [comment]
I hope you have read the requirements carefully. You need to create a react component which is responsive. 5 days to complete your task. Keep updating the PR :)

**Comment by nikita-1801** [comment]
I'm sorry I wasn't aware that we have to use react for this. I was just going to make it using HTML, CSS and JS. Are there any resources that you can recommend for using react here?

**Comment by ashishnagpal2498** [comment]
Okay, no issues. create using html, CSS. I'll help you converting that into react component. But it should meet other requirements i.e responsive mobile view. Cool ?

**Comment by nikita-1801** [comment]
Yes, sure!
