### ISSUE TITLE
Create Social Media Cards

### ISSUE THREAD

**Issue by ashishnagpal2498** [anushbhatia/Social-Scheduler#67]
You need to create a Social Media Icons component for the project.
1) The component will itself use another component which is card component ( Name accordingly). This will be a `shared component` which will take props and display the `social Media card` accordingly.
2) The Outer component should use flex boxes therefore should be responsive.
3) The card should open for additional information on click of icon (refer image). The additional information should not overlap lower components. (Use flexes, that will grow every box).
`Use styled components and bootstrap.`  You can improvise UX a bit. 
![Icons](https://user-images.githubusercontent.com/36301481/92524844-6b490e00-f240-11ea-954f-16012524c6dc.png)

**Comment by kritikaparmar-programmer** [comment]
I want to work on this issue.. Please assign me..

**Comment by shawavisek35** [comment]
I would like to work upon this issue

**Comment by ashishnagpal2498** [comment]
@kritikaparmar-programmer , assigning it to you. You got 5 days to complete it. Make sure to fulfill all the requirements mentioned above.

**Comment by ashishnagpal2498** [comment]
Keep in mind, your first PR is not supposed to be the best but a starting point for meeting the requirements, so do not wait until 5 days to show your work. Keep pushing your commits and getting feedback.

**Comment by kritikaparmar-programmer** [comment]
Hey @ashishnagpal2498 , I've one doubt where I've to put these cards like on the home page body?? 
Please help!

**Comment by kritikaparmar-programmer** [comment]
Sorry @ashishnagpal2498 , I thought it to do with html and css but not focused on the components part..
Sorry for the inconvenience.. I'm unassigning myself from this issue..

**Comment by ashishnagpal2498** [comment]
@shawavisek35 , would you like to work on this issue?

**Comment by shawavisek35** [comment]
Ok
I will work on this issue

**Comment by shawavisek35** [comment]
I have 2 question.
1. What will be the additional information that will displayed when opening a card?
2. Where this component will be displayed?

**Comment by shawavisek35** [comment]
ok
