### ISSUE TITLE
Create Events Card Component

### ISSUE THREAD

**Issue by ashishnagpal2498** [anushbhatia/Social-Scheduler#68]
You need to create a Events Card component for the project.
1) The component will itself use another component which is card component ( Name accordingly). This will be a shared component which will take props and display the content inside the card accordingly.
2) The Outer component should use flex boxes therefore should be responsive.
3) Card should display 3 events at a time and in total 5 events + view All button (in the end). Use bootstrap carousel or write custom JS (Upto you but movement should be smooth).
Reference - https://www.codeply.com/go/EIOtI7nkP8/bootstrap-carousel-with-multiple-cards ( The behavior of card should be like this, disable left initially, and right on full slide)
Cards should look like this - 
![upcomingEvents](https://user-images.githubusercontent.com/36301481/92584849-c830dc80-f2b1-11ea-90d0-9eecc18140ad.png)
- Use `styled components and bootstrap`. You can improvise UX a bit.

**Comment by shawavisek35** [comment]
Can you explain what do you mean by "The behavior of card should be like this, disable left initially, and right on full slide"?

**Comment by ashishnagpal2498** [comment]
Yes, I mean to say, if you refer the link I shared, the cards slide to left even if you are on 1st slide. So you have to enable slide on single side only. 
- Initial view     (left toggle (disabled)) (`<-`) Card 1 Card 2 Card 3 (`->`) (right toggle)
- Last slide view    (`<-`) Card 4 Card 5 view All (`->`)(right toggle button disabled).
This is what I mean to say. (It should not support circular rotation).

**Comment by AltCtrlDel1999** [comment]
Hey i would like to work on it

**Comment by ashishnagpal2498** [comment]
Okay @AltCtrlDel1999 , assigning it to you. You got 5 days to complete it.
Keep in mind, your first PR is not supposed to be the best but a starting point for meeting the requirements, so do not wait until 5 days to show your work. Keep pushing your commits and getting feedback.

**Comment by ashishnagpal2498** [comment]
Any updates on PR? @AltCtrlDel1999
