### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by anushbhatia** [anushbhatia/Social-Scheduler#7]
Basic Contact Form 

- [x] Adding Illustartion from Undraw
- [ ] Formspree for sending response to a specific id
- [ ] Adding Details of the mentors and contributors.

**Comment by chetnaSharma24** [comment]
i would like to resolve this issue.

**Comment by shawavisek35** [comment]
I would like to work upon this issue.

**Comment by shankhanil007** [comment]
I would like to work upon "Formspree for sending response to a specific id"

**Comment by shudhanshu03** [comment]
Assign me , I would like to work . Even i have started working on it

**Comment by anushbhatia** [comment]
Adding Illustartion from Undraw and basic form- @shawavisek35 
Formspree for sending response to a specific id @shankhanil007 
Adding Details of the mentors and contributors.-@chetnaSharma24  
@shudhanshu03 You can create the header for the contact page [like this](https://www.choicescreening.com/contact-choice-screening).

**Comment by chetnaSharma24** [comment]
how do i get the list of mentors and contributors?. would you please help me out

**Comment by smaranjitghose** [comment]
> how do i get the list of mentors and contributors?. would you please help me out

Project Maintainers: 
Anush Bhatia
Smaranjit Ghose

Contributors:
Just have a look at the Pull Request. Anyone who has got their Pull Request merged is a contributor (even you when you give the PR for this 😊)

**Comment by anushbhatia** [comment]
1st task is complete😎. Great work Team

**Comment by utchak160** [comment]
Can I work to make UI better and more responsive of contact Page?
