### ISSUE TITLE
Linking Contributor's card to their respective GitHub Profiles

### ISSUE THREAD

**Issue by tusharnankani** [anushbhatia/Social-Scheduler#72]
https://github.com/anushbhatia/Social-Scheduler/blob/9d347b6047d2e0c92349e57a010d473a0680ebd8/src/lib/contributers.js#L30

### Since, we are also fetching the `URL` to the contributor's profile, we can link to their username and their avatar in their Cards, over here:

https://github.com/anushbhatia/Social-Scheduler/blob/9d347b6047d2e0c92349e57a010d473a0680ebd8/src/components/Card.jsx#L8

https://github.com/anushbhatia/Social-Scheduler/blob/9d347b6047d2e0c92349e57a010d473a0680ebd8/src/components/Card.jsx#L10

**Comment by ashishnagpal2498** [comment]
Okay, I can assign you this work. Also there are few changes in contributors page which are need to be done.
1) The card class is a bootstrap class. Someone has messed up those classes with inline and external file CSS.
So you have to clean that file up. Make it simple, change existing or create new file and delete previous ones(up-to you, inspect thoroughly and delete css properties). 
Currently it looks like this.
![cardComp1 png](https://user-images.githubusercontent.com/36301481/93502658-a4fed080-f934-11ea-8f71-7e833eb220c8.jpg)
 - i) No need of margin-bottom in cards.
 - ii) Not aligned in center correctly.
![cardCompActual](https://user-images.githubusercontent.com/36301481/93502713-b7790a00-f934-11ea-9d99-c488dd4c76fa.png)
And should look somewhat like this, also center aligned.
2) Remove "contributor" text from the component, it is clear from the heading.
Will you work on this?

**Comment by tusharnankani** [comment]
Alright, working on it! @anushbhatia 

Just a few clarifications from my side: 
- I am new to Open Source and Development, I will try my best to fix it. 

>  A single card component for all admins, mentors, and contributors. No need to type-in separately.

- This will be difficult for me to implement.

Thank you! 
Tushar Nankani
^_^
