### ISSUE TITLE
Order of list of contributors.

### ISSUE THREAD

**Issue by tusharnankani** [anushbhatia/Social-Scheduler#76]
# Description

The order of the contributors' list is rather random.
- It can be arranged in maximum commits by contributors, directly from GitHub API.
- Or it can be arranged in alphabetical order.

## Type of issue

*These checkboxes can be checked like this: `[X]`*

- [X] Feature

## Checklist

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] I have added screenshots in case of bugs/feature updates.
- [X] This issue will be meaningful for the project.

### Screenshots

![Screenshot (490)](https://user-images.githubusercontent.com/61280281/93604438-febdd400-f9e2-11ea-94aa-94ca1b2e9833.png)

**Comment by ashishnagpal2498** [comment]
You would like to add filter option ( user can view two different ways) or you want to add by default ?

**Comment by tusharnankani** [comment]
I think we should lay the order out contribution-wise, instead of alphabetical. Also, I don't think the filter option is required.

**Comment by ashishnagpal2498** [comment]
I don't think there is as such of need for this. It can be additional to the project, but not necessary.
