### ISSUE TITLE
Mentors and Maintainers cards not yet linked.

### ISSUE THREAD

**Issue by tusharnankani** [anushbhatia/Social-Scheduler#77]
# Description

This is issue is in reference to #72 which was closed recently by this PR #75 from my side. 

- In the mentioned issue #72, this problem is yet to be dealt with.
> A single card component for all admins, mentors, and contributors. No need to type-in separately.

This was yet to be implemented since it is typed out for Mentors and Maintainers in [Detail.js](https://github.com/anushbhatia/Social-Scheduler/blob/master/src/components/Detail.js)

- If this cannot be implemented, then we can manually link it for the given 4 people in [Detail.js](https://github.com/anushbhatia/Social-Scheduler/blob/master/src/components/Detail.js)

## Type of issue

*These checkboxes can be checked like this: `[X]`*

- [ ] Feature (New Script)
- [X] Bug
- [ ] Documentation

## Checklist

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] I have added screenshots in case of bugs/feature updates.
- [X] This issue will be meaningful for the project.

### In case of bugs

- [X] I have added screenshots of the bug.
- [ ] I have added steps to reproduce the bug.
- [ ] I have proposed a possible solution for the bug.

### Screenshots

![Screenshot (491)](https://user-images.githubusercontent.com/61280281/93605146-fd40db80-f9e3-11ea-91d0-7cda2c11e395.png)

**Comment by ashishnagpal2498** [comment]
Since, contributors and all these cards will be merged. No need for this issue. :)
