### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by anushbhatia** [anushbhatia/Social-Scheduler#8]
Any bugs or issues in the current project will be added here

**Comment by utchak160** [comment]
The Footer code needs some formatting. Can I do this?

**Comment by ashishnagpal2498** [comment]
Broken image of HakinCodes. Correct readme file. 
![socialScheduler](https://user-images.githubusercontent.com/36301481/94441966-06d6fa00-01c1-11eb-9ba5-3c6e3bf97e71.png)

**Comment by ashishnagpal2498** [comment]
Broken image of HakinCodes. Correct readme file. 
![socialScheduler](https://user-images.githubusercontent.com/36301481/94441966-06d6fa00-01c1-11eb-9ba5-3c6e3bf97e71.png)

**Comment by akankshaprasad8** [comment]
can I work on this issue?
