### ISSUE TITLE
Contribute Md, correct links

### ISSUE THREAD

**Issue by ashishnagpal2498** [anushbhatia/Social-Scheduler#82]
# Description
'this' link and name of repo in contribution.md  are invalid. Correct those links.

## Type of issue
- [X] Bug
- [X] Documentation

### Screenshots
![image](https://user-images.githubusercontent.com/36301481/93714202-ba673b00-fb7e-11ea-9f18-2f34456b9f30.png)

**Comment by rajatgoel47** [comment]
can I work on this issue?
