### ISSUE TITLE
Show empty cards to contributors page with animation

### ISSUE THREAD

**Issue by ashishnagpal2498** [anushbhatia/Social-Scheduler#86]
# Description
Since data is fetched from API, there can be a slight delay. To avoid empty view we want to show empty cards.
Reference Image - 
![empty state](https://user-images.githubusercontent.com/36301481/94350712-830cf880-006e-11eb-888b-ba6911e469ed.png)
## Type of issue

- [X ] Feature (New Script)

**Comment by ashishsahu1** [comment]
Hey Ashish I want to work in this issue, can you explain the work a little bit more?
